package mil.army.usace.hec.dss.tools;

import java.io.IOException;
import java.io.PrintWriter;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;

/**
 * Deterministic public-API snapshot tool.
 *
 * <p>Walks the {@code mil.army.usace.hec.dss} package (non-recursive — the
 * {@code .internal} subpackage is skipped) and emits a stable text listing of
 * every public type, field, constructor, and method.
 *
 * <p>Usage: {@code java mil.army.usace.hec.dss.tools.ApiSnapshot <classes-dir> <output-file>}
 *
 * <p>The output is intended to be committed to the repo as
 * {@code api/public-api.txt}. PRs that change the public API show up as a diff
 * in this file — reviewers can see additions, removals, and signature changes
 * at a glance.
 */
public final class ApiSnapshot {
    private static final String PUBLIC_PACKAGE = "mil.army.usace.hec.dss";
    private static final String INTERNAL_PREFIX = PUBLIC_PACKAGE + ".internal";

    public static void main(String[] args) throws Exception {
        if (args.length != 2) {
            System.err.println("Usage: ApiSnapshot <classes-dir> <output-file>");
            System.exit(2);
        }
        Path classesDir = Path.of(args[0]);
        Path outputFile = Path.of(args[1]);

        List<Class<?>> types = loadPublicTypes(classesDir);
        types.sort(Comparator.comparing(Class::getName));

        Files.createDirectories(outputFile.getParent());
        try (PrintWriter out = new PrintWriter(Files.newBufferedWriter(outputFile))) {
            out.println("# hec-dss-java public API snapshot");
            out.println("# Generated by ApiSnapshot — do not edit by hand.");
            out.println("# Regenerate with: ./gradlew apiSnapshot");
            out.println("# Package: " + PUBLIC_PACKAGE + " (excluding .internal)");
            out.println();
            for (Class<?> type : types) {
                emitType(out, type);
                out.println();
            }
        }
        System.out.println("Wrote " + outputFile);
    }

    private static List<Class<?>> loadPublicTypes(Path classesDir) throws IOException {
        List<Class<?>> types = new ArrayList<>();
        try (Stream<Path> walk = Files.walk(classesDir)) {
            walk.filter(p -> p.toString().endsWith(".class")).forEach(p -> {
                String rel = classesDir.relativize(p).toString();
                String binaryName = rel.substring(0, rel.length() - ".class".length())
                        .replace('/', '.').replace('\\', '.');
                if (!binaryName.startsWith(PUBLIC_PACKAGE)) return;
                if (binaryName.startsWith(INTERNAL_PREFIX)) return;
                // Skip package-info, module-info, and any non-direct types
                if (binaryName.endsWith("package-info") || binaryName.equals("module-info")) return;
                try {
                    Class<?> c = Class.forName(binaryName, false, ApiSnapshot.class.getClassLoader());
                    if (Modifier.isPublic(c.getModifiers()) || Modifier.isProtected(c.getModifiers())) {
                        types.add(c);
                    }
                } catch (Throwable t) {
                    System.err.println("WARN: could not load " + binaryName + ": " + t.getMessage());
                }
            });
        }
        return types;
    }

    private static void emitType(PrintWriter out, Class<?> type) {
        out.println(typeHeader(type) + " {");

        Field[] fields = type.getDeclaredFields();
        Arrays.sort(fields, Comparator.comparing(Field::getName));
        for (Field f : fields) {
            if (!isApiVisible(f.getModifiers())) continue;
            out.println("  " + fieldSignature(f));
        }

        Constructor<?>[] ctors = type.getDeclaredConstructors();
        Arrays.sort(ctors, Comparator.comparing(ApiSnapshot::ctorKey));
        for (Constructor<?> c : ctors) {
            if (!isApiVisible(c.getModifiers())) continue;
            out.println("  " + ctorSignature(type, c));
        }

        Method[] methods = type.getDeclaredMethods();
        Arrays.sort(methods, Comparator.comparing(ApiSnapshot::methodKey));
        for (Method m : methods) {
            if (!isApiVisible(m.getModifiers())) continue;
            if (m.isSynthetic() || m.isBridge()) continue;
            out.println("  " + methodSignature(m));
        }

        out.println("}");
    }

    private static String typeHeader(Class<?> type) {
        StringBuilder sb = new StringBuilder();
        sb.append(modifierString(type.getModifiers())).append(" ");
        if (type.isInterface()) sb.append("interface ");
        else if (type.isEnum()) sb.append("enum ");
        else if (type.isRecord()) sb.append("record ");
        else sb.append("class ");
        sb.append(type.getName());
        if (type.isRecord()) {
            sb.append("(");
            var components = type.getRecordComponents();
            for (int i = 0; i < components.length; i++) {
                if (i > 0) sb.append(", ");
                sb.append(typeName(components[i].getType())).append(" ").append(components[i].getName());
            }
            sb.append(")");
        }
        Class<?> superClass = type.getSuperclass();
        if (superClass != null && superClass != Object.class
                && superClass != Enum.class && superClass != Record.class) {
            sb.append(" extends ").append(superClass.getName());
        }
        Class<?>[] ifaces = type.getInterfaces();
        if (ifaces.length > 0) {
            sb.append(type.isInterface() ? " extends " : " implements ");
            for (int i = 0; i < ifaces.length; i++) {
                if (i > 0) sb.append(", ");
                sb.append(ifaces[i].getName());
            }
        }
        return sb.toString();
    }

    private static String fieldSignature(Field f) {
        return modifierString(f.getModifiers()) + " "
                + typeName(f.getType()) + " " + f.getName() + ";";
    }

    private static String ctorSignature(Class<?> type, Constructor<?> c) {
        return modifierString(c.getModifiers()) + " "
                + simpleName(type) + "(" + paramList(c.getParameterTypes()) + ");";
    }

    private static String methodSignature(Method m) {
        return modifierString(m.getModifiers()) + " "
                + typeName(m.getReturnType()) + " " + m.getName()
                + "(" + paramList(m.getParameterTypes()) + ");";
    }

    private static String paramList(Class<?>[] params) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < params.length; i++) {
            if (i > 0) sb.append(", ");
            sb.append(typeName(params[i]));
        }
        return sb.toString();
    }

    private static String typeName(Class<?> c) {
        if (c.isArray()) return typeName(c.getComponentType()) + "[]";
        return c.getName();
    }

    private static String simpleName(Class<?> c) {
        String name = c.getName();
        int dot = name.lastIndexOf('.');
        int dollar = name.lastIndexOf('$');
        return name.substring(Math.max(dot, dollar) + 1);
    }

    private static String modifierString(int mods) {
        // Keep only api-visible modifiers; ignore synthetic/varargs bits and the like.
        return Modifier.toString(mods & (Modifier.PUBLIC | Modifier.PROTECTED | Modifier.PRIVATE
                | Modifier.STATIC | Modifier.FINAL | Modifier.ABSTRACT));
    }

    private static boolean isApiVisible(int mods) {
        return Modifier.isPublic(mods) || Modifier.isProtected(mods);
    }

    private static String ctorKey(Constructor<?> c) {
        return paramList(c.getParameterTypes());
    }

    private static String methodKey(Method m) {
        return m.getName() + "|" + paramList(m.getParameterTypes());
    }

    private ApiSnapshot() {}
}
